server:
  port: 12010
  servlet:
    context-path: /mypass-manager/auth/
spring:
  profiles:
    default: configserver
  application:
    name: authorization-server
  mvc:
    static-path-pattern: /content/**
  cloud:
    config.enabled: false
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:eureka@localhost:8761/eureka
  instance:
    prefer-ip-address: true
springdoc:
  version: @project.version@
  title: @project.name@
  description: @project.description@
  license-name: 'MIT'
  license-url: 'https://github.com/marcoshssilva/MHPasswordManager/blob/main/LICENSE'
  swagger-ui:
    oauth2-redirect-url: ${SPRINGDOC_SWAGGERUI_OAUTH2_REDIRECT_URL:http://127.0.0.1:12010/swagger-ui/redirect}
    oauth2-authorization-url: ${SPRINGDOC_SWAGGERUI_OAUTH2_AUTHORIZATION_URL:http://127.0.0.1:12010/oauth2/authorize} # custom doesn't exist on springdoc open-api
    oauth2-token-url: ${SPRINGDOC_SWAGGERUI_OAUTH2_TOKEN_URL:http://127.0.0.1:12010/oauth2/token} # custom doesn't exist on springdoc open-api
    csrf:
      enabled: true
config:
  gateway:
    allowed.configserver.code: ${CONFIG_GATEWAY_ALLOWED_CONFIGSERVER_CODE:6a0fb275-b928-83e9-b42a-8f7020e95ec6}
  mail:
    queues-key:
      send-event: ${CONFIG_MAIL_QUEUES_KEY_SEND_EVENT:email.send-event}