spring:
  cloud:
    config:
      discovery:
        enabled: false
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    # REQUIRED ONLY if you want to use config.users.mode=DATABASE, unless not needed
    users:
      username: 'sa-authorization-server'
      password: 'P@sswordAuthS3rv3r'
      url: 'jdbc:postgresql://127.0.0.1:5432/db_users'
    auth:
      username: 'sa-authorization-server'
      password: 'P@sswordAuthS3rv3r'
      url: 'jdbc:postgresql://localhost:5432/db_auth'
  flyway:
    enabled: true
    url: ${spring.datasource.auth.url}
    user: ${spring.datasource.auth.username}
    password: ${spring.datasource.auth.password}
    schemas:
      - public
  session:
    store-type: redis
  redis:
    host: 127.0.0.1
    password: 'MHP@SSW0R3#20230401' # default no password, for set use SPRING_REDIS_PASSWORD or -Dspring.redis.password
    port: 6379
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    virtual-host: vhost-password-manager
    username: authorization-server-pm
    password: authorization-server-pm-P@ss
config:
  jwk:
    mode: DATABASE
  oauth:
    mode: DATABASE
    server-settings:
      issuer-uri: http://127.0.0.1:8080${server.servlet.context-path}
  users:
    mode: WEB_CLIENT
    webclient:
      base-url: http://USER-SERVICE/mypass-manager/users
      request-timeout: 5s
      oauth2:
        registration-id: passwordmanager-global
        client-id: MHPasswordManager-GlobalAdmin
        client-secret: 9f45dc98-8e4f-11ee-b9d1-0242ac120002
        token-uri: ${config.oauth.server-settings.issuer-uri}/oauth2/token
        scopes: global:fullAccess
springdoc:
  swagger-ui:
    oauth2-redirect-url: ${SPRINGDOC_SWAGGERUI_OAUTH2_REDIRECT_URL:http://127.0.0.1:12010/mypass-manager/auth/swagger-ui/redirect}
    oauth2-authorization-url: ${SPRINGDOC_SWAGGERUI_OAUTH2_AUTHORIZATION_URL:http://127.0.0.1:12010/mypass-manager/auth/oauth2/authorize} # custom doesn't exist on springdoc open-api
    oauth2-token-url: ${SPRINGDOC_SWAGGERUI_OAUTH2_TOKEN_URL:http://127.0.0.1:12010/mypass-manager/auth/oauth2/token} # custom doesn't exist on springdoc open-api