services:
  config:
    restart: on-failure
    build:
      context: ./mhpasswordmanager-config-services
    env_file:
      - etc/env/CONFIG-SERVICES.env
    depends_on:
      eureka:
        condition: service_healthy
    networks:
      - net
    ports:
      - "8888:8888"
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:8888/actuator/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
    profiles:
      - apps
      - all
  eureka:
    restart: on-failure
    build:
      context: ./mhpasswordmanager-service-registry
    env_file:
      - etc/env/SERVICE-REGISTRY.env
    networks:
      - net
    ports:
      - "8761:8761"
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:8761/actuator/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
    profiles:
      - apps
      - all
  oauth2-server:
    restart: on-failure
    build:
      context: ./mhpasswordmanager-oauth2-server
    env_file:
      - etc/env/OAUTH2-AUTHORIZATION-SERVER.env
    depends_on:
      redis:
        condition: service_healthy
      eureka:
        condition: service_healthy
      postgres-db:
        condition: service_healthy
      config:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      user-service:
        condition: service_healthy
    networks:
      - net
    ports:
      - "12010:12010"
    profiles:
      - apps
      - all
  gateway:
    restart: on-failure
    build:
      context: ./mhpasswordmanager-api-gateway
    env_file:
      - etc/env/API-GATEWAY.env
    depends_on:
      eureka:
        condition: service_healthy
      user-service:
        condition: service_healthy
      password-service:
        condition: service_healthy
      email-service:
        condition: service_healthy
      file-service:
        condition: service_healthy
      oauth2-server:
        condition: service_healthy
    networks:
      - net
    ports:
      - "8080:8080"
    profiles:
      - apps
      - all
  user-service:
    restart: on-failure
    build:
      context: ./mhpasswordmanager-user-service
    env_file:
      - etc/env/USER-SERVICE.env
    depends_on:
      eureka:
        condition: service_healthy
      postgres-db:
        condition: service_healthy
      config:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - net
    ports:
      - "12011:12011"
    profiles:
      - apps
      - all
  password-service:
    restart: on-failure
    build:
      context: ./mhpasswordmanager-password-service
    env_file:
      - etc/env/PASSWORD-SERVICE.env
    depends_on:
      eureka:
        condition: service_healthy
      postgres-db:
        condition: service_healthy
      config:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - net
    ports:
      - "12012:12012"
    profiles:
      - apps
      - all
  email-service:
    restart: on-failure
    build:
      context: ./mhpasswordmanager-email-service
    env_file:
      - etc/env/EMAIL-SERVICE.env
    networks:
      - net
    depends_on:
      eureka:
        condition: service_healthy
      config:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      mailserver:
        condition: service_healthy
    profiles:
      - apps
      - all
  file-service:
    restart: on-failure
    build:
      context: ./mhpasswordmanager-file-service
    env_file:
      - etc/env/FILE-SERVICE.env
    ports:
      - "12014:12014"
    networks:
      - net
    depends_on:
      eureka:
        condition: service_healthy
      config:
        condition: service_healthy
      redis:
        condition: service_healthy
      mongo:
        condition: service_healthy
    profiles:
      - apps
      - all
  postgres-db:
    restart: on-failure
    build:
      context: ./etc/docker/tool-postgres
    env_file:
      - etc/env/POSTGRES-DB.env
    networks:
      - net
    ports:
      - "5432:5432"
    volumes:
      - data-postgres-db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    profiles:
      - tools
      - all
  redis:
    env_file:
      - etc/env/REDIS-STORE.env
    restart: on-failure
    build:
      context: ./etc/docker/tool-redis
    ports:
      - '6379:6379'
    volumes:
      - data-redis:/data
    networks:
      - net
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    profiles:
      - tools
      - all
  mongo:
    restart: on-failure
    build:
      context: ./etc/docker/tool-mongo
    env_file:
      - etc/env/MONGO-DB.env
    networks:
      - net
    volumes:
      - data-mongo-db:/data/db
    ports:
      - "27017:27017"
    healthcheck:
      test: ["CMD-SHELL", "mongosh --eval 'db.runCommand({ping:1})'"]
      interval: 10s
      timeout: 5s
      retries: 5
    profiles:
      - tools
      - all
  rabbitmq:
    restart: on-failure
    build:
      context: ./etc/docker/tool-rabbitmq
    env_file:
      - etc/env/RABBITMQ.env
    networks:
      - net
    volumes:
      - data-rabbitmq-data:/var/lib/rabbitmq
      - data-rabbitmq-logs:/var/log/rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
      - "25672:25672"
      - "15692:15692"
    healthcheck:
      test: ["CMD-SHELL", "rabbitmq-diagnostics -q check_running"]
      interval: 10s
      timeout: 5s
      retries: 5
    profiles:
      - tools
      - all
  mailserver:
    restart: on-failure
    build:
      context: ./etc/docker/tool-mail
    env_file:
      - etc/env/MAILSERVER.env
    networks:
      - net
    ports:
      - "1025:1025"
      - "1080:1080"
    healthcheck:
      test: ["CMD-SHELL", "wget -q --spider http://localhost:1080 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
    profiles:
      - tools
      - all
networks:
  net:
    driver: bridge
volumes:
  data-postgres-db:
  data-redis:
  data-mongo-db:
  data-rabbitmq-logs:
  data-rabbitmq-data: