gateway.allowed.configserver.code: ${GATEWAY_ALLOWED_CONFIGSERVER_CODE:6a0fb275-b928-83e9-b42a-8f7020e95ec6}
server:
  port: 12014
  servlet:
    context-path: /mypass-manager/files
spring:
  #  profiles:
  #    default: local
  application:
    name: file-service
  cloud:
    config:
      discovery:
        enabled: true
        service-id: ${SPRING_CLOUD_DISCOVERY_SERVICE_ID:config-server}
      headers:
        X-Gateway-Auth: ${gateway.allowed.configserver.code:changeit}
        X-Service-Name: ${spring.application.name}
  config:
    import: "optional:configserver:"
  servlet:
    multipart:
      enabled: true
      max-file-size: 96MB
      max-request-size: 110MB
      resolve-lazily: false
  session:
    store-type: none
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:eureka@localhost:8761/eureka
  instance:
    prefer-ip-address: true
springdoc:
  version: @project.version@
  title: @project.name@
  description: @project.description@
  license-name: 'MIT'
  license-url: 'https://github.com/marcoshssilva/MHPasswordManager/blob/main/LICENSE'