spring:
  cloud:
    config.enabled: false
  config:
    import: ""
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: http://mhpasswordmanager.test.fake.com
eureka:
  client:
    enabled: false
    register-with-eureka: false
    fetch-registry: false
storage:
  s3:
    endpoint: http://127.0.0.1:9000
    region: us-east-1
    bucket: mhp-files
    access-key: test-access-key
    secret-key: test-secret-key
    path-style-access: true
