spring:
  cloud:
    config.enabled: false
  config:
    import: ""
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: http://mhpasswordmanager.test.fake.com
eureka:
  client:
    enabled: false
    register-with-eureka: false
    fetch-registry: false
