spring:
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: http://mhpasswordmanager.test.fake.com
#eureka:
#  instance:
#    hostname: localhost
#    prefer-ip-address: true
#  client:
#    enabled: false
