server:
  port: 12014
  servlet:
    context-path: /mypass-manager/files
spring:
  profiles:
    default: configserver
  application:
    name: file-service
  cloud:
    config:
      enabled: false
  servlet:
    multipart:
      enabled: true
      max-file-size: 96MB
      max-request-size: 110MB
      resolve-lazily: false
  session:
    store-type: none
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
springdoc:
  version: @project.version@
  title: @project.name@
  description: @project.description@
  license-name: 'MIT'
  license-url: 'https://github.com/marcoshssilva/MHPasswordManager/blob/main/LICENSE'