@Library('java@main') _
pipelineJavaWithPublicImage(
    'MHPasswordManagerApiGateway', 
    '17.0.8-oracle', 
    '3.9.6'
    'mhpasswordmanager-api-gateway', 
    false, 
    false, 
    false, 
    'password-manager/api-gateway')
