server:
  port: ${PORT:8080}
spring:
  application:
    name: 'gateway'
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: '*'
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - HEAD
              - OPTIONS
            allowedHeaders:
              - Content-type
              - Authorization
      routes:
        - id: authorization-server
          uri: lb://AUTHORIZATION-SERVER
          predicates:
            - Path=/mypass-manager/auth/**
          filters:
            - PreserveHostHeader
          metadata:
            connect-timeout: 3000
            response-timeout: 10s
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/mypass-manager/users/**
          filters:
            - RewritePath=/mypass-manager/users/(?<segment>.*),/mypass-manager/users/$\{segment}
            - PreserveHostHeader
          metadata:
            connect-timeout: 3000
            response-timeout: 10s
        - id: password-service
          uri: lb://PASSWORD-SERVICE
          predicates:
            - Path=/mypass-manager/passwords/**
          filters:
            - RewritePath=/mypass-manager/passwords/(?<segment>.*),/mypass-manager/passwords/$\{segment}
            - PreserveHostHeader
          metadata:
            connect-timeout: 3000
            response-timeout: 10s
        - id: email-service
          uri: lb://EMAIL-SERVICE
          predicates:
            - Path=/mypass-manager/emails/**
          filters:
            - RewritePath=/mypass-manager/emails/(?<segment>.*),/mypass-manager/emails/$\{segment}
            - PreserveHostHeader
          metadata:
            connect-timeout: 3000
            response-timeout: 10s
        - id: file-service
          uri: lb://FILE-SERVICE
          predicates:
            - Path=/mypass-manager/files/**
          filters:
            - RewritePath=/mypass-manager/files/(?<segment>.*),/mypass-manager/files/$\{segment}
            - PreserveHostHeader
          metadata:
            connect-timeout: 3000
            response-timeout: 10s
        - id: eureka
          uri: lb://EUREKA-SERVICE-REGISTRY
          predicates:
            - Path=/eureka/**
            - Host=${GATEWAY_ALLOWED_EUREKA_HOSTS:localhost,127.0.0.1,host.docker.internal}
            - Header=X-Gateway-Auth,${GATEWAY_ALLOWED_EUREKA_CODE:changeit}
          filters:
            - RewritePath=/eureka/(?<segment>.*),/eureka/$\{segment}
            - PreserveHostHeader
          metadata:
            connect-timeout: 3000
            response-timeout: 10s
        - id: config-server
          uri: lb://CONFIG-SERVER
          predicates:
            - Path=/config/**
            - Host=${GATEWAY_ALLOWED_CONFIGSERVER_HOSTS:localhost,127.0.0.1,host.docker.internal}
            - Header=X-Gateway-Auth,${GATEWAY_ALLOWED_CONFIGSERVER_CODE:changeit}
          filters:
            - RewritePath=/config/(?<segment>.*),/$\{segment}
            - PreserveHostHeader
          metadata:
            connect-timeout: 3000
            response-timeout: 10s
        - id: default_route
          uri: no://op
          filters:
            - PreserveHostHeader
            - RedirectTo=302,${SPRING_CLOUD_GATEWAY_DEFAULT_ROUTE:http://127.0.0.1:8080/mypass-manager/auth/}
          predicates:
            - Path=/**
management:
  server:
    port: ${MANAGEMENT_PORT:8081}
  endpoint:
    shutdown:
      enabled: false
    health:
      show-components: always
      show-details: always
  endpoints:
    jmx:
      exposure.include: '*'
    web:
      exposure.include: '*'
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:eureka@localhost:8761/eureka
  instance:
    prefer-ip-address: true