DROP TABLE IF EXISTS db_users.group_members;
DROP TABLE IF EXISTS db_users.group_authorities;
DROP TABLE IF EXISTS db_users.groups;

create table db_users.groups
(
    id         bigint GENERATED BY DEFAULT AS IDENTITY (START WITH 1),
    group_name varchar(50) NOT NULL,
    PRIMARY KEY (id)
);

create table db_users.group_authorities
(
    group_id  bigint      NOT NULL,
    authority varchar(50) NOT NULL,
    CONSTRAINT fk_group_authorities_group FOREIGN KEY (group_id) REFERENCES db_users.groups (id)
);

create table db_users.group_members
(
    id       bigint GENERATED BY DEFAULT AS IDENTITY (START WITH 1),
    username varchar(50) NOT NULL,
    group_id bigint      NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT fk_group_members_group FOREIGN KEY (group_id) REFERENCES db_users.groups (id)
);