spring:
  cloud:
    config:
      enabled: true
      discovery:
        enabled: true
        service-id: ${SPRING_CLOUD_DISCOVERY_SERVICE_ID:config-server}
      headers:
        X-Gateway-Auth: ${config.gateway.allowed.configserver.code}
        X-Service-Name: ${spring.application.name}
  config:
    import: "optional:configserver:"
