DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS users_details CASCADE;
DROP TABLE IF EXISTS authorities CASCADE;
DROP TABLE IF EXISTS groups CASCADE;
DROP TABLE IF EXISTS group_authorities CASCADE;
DROP TABLE IF EXISTS group_members CASCADE;

create table users
(
    username varchar(255) NOT NULL,
    password varchar(255) NOT NULL,
    enabled  boolean     NOT NULL,
    PRIMARY KEY (username)
);

create table authorities
(
    username  varchar(255) NOT NULL,
    authority varchar(50) NOT NULL,
    CONSTRAINT fk_authorities_users FOREIGN KEY (username) REFERENCES users (username)
);
create unique index ix_auth_username on authorities (username, authority);

create table groups
(
    id         bigint GENERATED BY DEFAULT AS IDENTITY (START WITH 1),
    group_name varchar(50) NOT NULL,
    PRIMARY KEY (id)
);

create table group_authorities
(
    group_id  bigint      NOT NULL,
    authority varchar(50) NOT NULL,
    CONSTRAINT fk_group_authorities_group FOREIGN KEY (group_id) REFERENCES groups (id)
);

create table group_members
(
    id       bigint GENERATED BY DEFAULT AS IDENTITY (START WITH 1),
    username varchar(255) NOT NULL,
    group_id bigint      NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT fk_group_members_group FOREIGN KEY (group_id) REFERENCES groups (id)
);

CREATE TABLE users_details
(
    username  varchar(50) NOT NULL,
    firstName varchar(36) NOT NULL,
    lastName  varchar(36) NOT NULL,
    imageUrl  varchar(255),
    PRIMARY KEY (username),
    CONSTRAINT fk_user_details_users FOREIGN KEY (username) REFERENCES users (username)
        ON DELETE RESTRICT
        ON UPDATE CASCADE
);

INSERT INTO users (username, password, enabled)
VALUES ('johndoe@email.com',
        '$2a$10$6EG8N4N7jbOsY/RNPTK98eL2vft7ig7SPO/IOFd.PdnL66HgI6oDe',
        true),
       ('emmywatson@email.com',
        '$2a$10$BGG3r6z9udsLHBKLXZV0iuDvPdChNaEVoFINr.Myh0l2iEEwU.tFm',
        true),
       ('marcoshssilva.dev@gmail.com',
        '$2a$10$KkW5uV9JjrRJ13/56.5h.e.qovf4YMlxCR7FhZngm7/2m/HLDG7dO',
        true);

INSERT INTO authorities (username, authority)
VALUES ('johndoe@email.com',
        'ROLE_ADMIN'),
       ('johndoe@email.com',
        'ROLE_USER'),
       ('emmywatson@email.com',
        'ROLE_USER'),
       ('marcoshssilva.dev@gmail.com',
        'ROLE_ADMIN'),
       ('marcoshssilva.dev@gmail.com',
        'ROLE_MASTER'),
       ('marcoshssilva.dev@gmail.com',
        'ROLE_USER');

INSERT INTO users_details (username, firstName, lastName, imageUrl)
VALUES ('marcoshssilva.dev@gmail.com',
        'Marcos',
        'Silva',
        null),
       ('johndoe@email.com',
        'John',
        'Doe',
        null),
       ('emmywatson@email.com',
        'Emmy',
        'Watson',
        null);