create table users
(
    username varchar(255) NOT NULL,
    password varchar(255) NOT NULL,
    enabled  boolean      NOT NULL,
    PRIMARY KEY (username)
);

create table authorities
(
    username  varchar(255) NOT NULL,
    authority varchar(255) NOT NULL,
    CONSTRAINT fk_authorities_users FOREIGN KEY (username) REFERENCES users (username)
);
create unique index ix_auth_username on authorities (username, authority);

create table groups
(
    id         bigint GENERATED BY DEFAULT AS IDENTITY (START WITH 1),
    group_name varchar(255) NOT NULL,
    PRIMARY KEY (id)
);

create table group_authorities
(
    group_id  bigint      NOT NULL,
    authority varchar(255) NOT NULL,
    CONSTRAINT fk_group_authorities_group FOREIGN KEY (group_id) REFERENCES groups (id)
);

create table group_members
(
    id       bigint GENERATED BY DEFAULT AS IDENTITY (START WITH 1),
    username varchar(255) NOT NULL,
    group_id bigint      NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT fk_group_members_group FOREIGN KEY (group_id) REFERENCES groups (id)
);

CREATE TABLE users_details
(
    username  varchar(255) NOT NULL,
    firstName varchar(255) NOT NULL,
    lastName  varchar(255) NOT NULL,
    imageUrl  varchar(255),
    PRIMARY KEY (username),
    CONSTRAINT fk_user_details_users FOREIGN KEY (username) REFERENCES users (username)
        ON DELETE RESTRICT
        ON UPDATE CASCADE
);

CREATE TABLE oauth2_jwk_keys
(
    uuid               varchar(36) NOT NULL,
    algorithm          varchar(10) NOT NULL DEFAULT 'RSA',
    base64_private_key text        NOT NULL,
    base64_public_key  text        NOT NULL,
    created_at         timestamp   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at         timestamp,
    active             boolean     NOT NULL DEFAULT false,
    PRIMARY KEY (uuid)
);