otel:
  sdk:
    disabled: ${OTEL_SDK_DISABLED:false}
  exporter:
    otlp:
      endpoint: ${OTEL_EXPORTER_OTLP_ENDPOINT:http://localhost:4318}
      protocol: ${OTEL_EXPORTER_OTLP_PROTOCOL:http/protobuf}
      headers: ${OTEL_EXPORTER_OTLP_HEADERS:}
  instrumentation:
    common:
      default-enabled: true
    jdbc:
      enabled: true
    log4j-appender:
      enabled: true
    logback-mdc:
      enabled: true
    spring-web:
      enabled: true
    spring-webmvc:
      enabled: true
    spring-webflux:
      enabled: true
    kafka:
      enabled: true
    mongo:
      enabled: true
    micrometer:
      enabled: true
    r2dbc:
      enabled: true
  resource:
    attributes_list: ${OTEL_RESOURCE_ATTRIBUTES:}
    attributes:
      - name: deployment.environment
        value: ${ENV:LOCAL}
      - name: service.name
        value: ${OTEL_SERVICE_NAME:${spring.application.name}}
      - name: service.namespace
        value: ${OTEL_SERVICE_NAMESPACE:${spring.application.name}}
      - name: service.version
        value: ${APP_VERSION:unknown}
      - name: service.instance.id
        value: ${OTEL_SERVICE_INSTANCE_ID:${HOSTNAME:${random.uuid}}}
      - name: host.name
        value: ${HOSTNAME:localhost}
      - name: application.domain
        value: ${APPLICATION_DOMAIN:default}
      - name: application.team
        value: ${APPLICATION_TEAM:unknown}
      - name: spring.profiles.active
        value: ${spring.profiles.active:default}
      - name: spring.application.group
        value: ${SPRING_APPLICATION_GROUP:default}
      - name: cloud.provider
        value: ${CLOUD_PROVIDER:none}
      - name: cloud.region
        value: ${CLOUD_REGION:local}