springdoc:
  show-actuator: true # list actuator endpoints into Swagger
  show-login-endpoint: false # -- dont need more, prefer OAuth2 @SecurityScheme
  swagger-ui:
    oauth:
      client-id: MHPasswordManager
      client-secret: b07968bd-8989-4f10-82c7-3e427e22c924
      use-basic-authentication-with-access-code-grant: on
management:
  endpoint:
    health:
      group:
        integrations:
          show-components: when_authorized
          show-details: when_authorized
          include:
            - db
            - rabbit
            - mail
    shutdown:
      enabled: false
  endpoints:
    web:
      exposure:
        include:
          - 'health'
          - 'info'
          - 'metrics'
          - 'mail'
---
spring:
  config:
    activate:
      on-profile: docker0
  session:
    store-type: redis
  redis:
    host: redis
    password: 'MHP@SSW0R3#20230401'
    port: 6379
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: http://host.docker.internal:8080/mypass-manager/auth/
  rabbitmq:
    host: rabbitmq
    virtual-host: vhost-password-manager
    username: email-service-pm
    password: email-service-pm-P@ss
  mail:
    host: mailserver
    # username: johndoe
    # password: F4k3P@ss
    properties:
      mail.transport.protocol: smtp
      mail.smtp.auth: false
      mail.smtp.port: 1025
      mail.smtp.starttls.enable: false
      mail.smtp.starttls.required: false
application:
  email:
    type: mail
    default-sender: no-reply@localhost.fake.mail.com
    enable-redirect-mail: false
    address-redirect-mail: no-reply@localhost.fake.mail.com
springdoc:
  show-actuator: true
  show-login-endpoint: false
  swagger-ui:
    oauth2-authorization-url: http://127.0.0.1:8080/mypass-manager/auth/oauth2/authorize
    oauth2-token-url: http://127.0.0.1:8080/mypass-manager/auth/oauth2/token
    oauth2-redirect-url: http://127.0.0.1:8080/mypass-manager/emails/swagger-ui/redirect
    csrf:
      enabled: true