springdoc:
  show-actuator: true # list actuator endpoints into Swagger
  show-login-endpoint: false # -- dont need more, prefer OAuth2 @SecurityScheme
  swagger-ui:
    oauth:
      client-id: MHPasswordManager
      client-secret: b07968bd-8989-4f10-82c7-3e427e22c924
      use-basic-authentication-with-access-code-grant: on
management:
  endpoint:
    health:
      group:
        integrations:
          show-components: when_authorized
          show-details: when_authorized
          include:
            - db
    shutdown:
      enabled: false
  endpoints:
    web:
      exposure:
        include:
          - health
          - metrics
          - info
---
spring:
  config:
    activate:
      on-profile: docker0
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgres-db:5432/db_users
    username: 'sa-user-service'
    password: 'P@ssw0rdUs3rS3rvic3'
  session:
    store-type: none
  flyway:
    enabled: true
    driver-class-name: org.postgresql.Driver
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    schemas:
      - 'public'
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      dialect: org.hibernate.dialect.PostgreSQLDialect
  jackson:
    default-property-inclusion: non_null
    serialization:
      fail-on-empty-beans: false
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: http://host.docker.internal:8080/mypass-manager/auth/
springdoc:
  show-actuator: true
  show-login-endpoint: false
  swagger-ui:
    oauth2-authorization-url: http://127.0.0.1:8080/mypass-manager/auth/oauth2/authorize
    oauth2-token-url: http://127.0.0.1:8080/mypass-manager/auth/oauth2/token
    oauth2-redirect-url: http://127.0.0.1:8080/mypass-manager/users/swagger-ui/redirect
    csrf:
      enabled: false